/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaodien;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nvcam
 */
public class docgia extends javax.swing.JFrame {

    /**
     * Creates new form docgia
     */
    public docgia() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        hienthi();
    }
    private void loadTenTK(String matk) {
        String sql = "SELECT taikhoan FROM TaiKhoan WHERE matk like N'%" + matk + "%'";
        Connection connection =DBconnection.geConnection();
        try{
            java.sql.Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                this.txtTKDG.setText("Chào mừng ( "+ rs.getString("taikhoan")+" )");
            }
        }catch(Exception e){

        }
        
    }
    
    public docgia(String matk) {
        initComponents();
        this.setLocationRelativeTo(null);
        hienthi();
        loadTenTK(matk);
        showDuLieuDocGia(matk);
        try {
            tblDSMuon.removeAll();
            String [] arr = {"Mã phiếu mượn ","Mã độc giả","Mã tài khoản","Tên độc giả ","Tên Sách ","Số lượng ","Ngày mượn","Số ngày mượn", "Ghi chú","Trạng Thái "};
            DefaultTableModel model;
            model = new DefaultTableModel(arr, 0);

            Connection connection =DBconnection.geConnection();

            String query = "select PM.mapm,DG.madg , DG.matk, DG.hoten, S.tensach, PM.soluong, PM.ngaymuon, PM.songaymuon, PM.ghichu, PM.trangthai from DocGia DG inner join Phieumuon PM on DG.madg = PM.madg inner join Sach S on PM.mas = S.mas where DG.matk = '"+matk+"' ";
            java.sql.Statement statement =  connection.createStatement();
            ResultSet rs = statement.executeQuery(query);
            while(rs.next()) {
                Vector vct = new Vector();
                vct.add(rs.getString("mapm"));
                vct.add(rs.getString("madg"));
                vct.add(rs.getString("matk"));
                vct.add(rs.getString("hoten"));
                vct.add(rs.getString("tensach"));
                vct.add(rs.getString("soluong"));
                vct.add(rs.getString("ngaymuon"));
                vct.add(rs.getString("songaymuon"));
                vct.add(rs.getString("ghichu"));
                vct.add(rs.getString("trangthai"));
                
                model.addRow(vct);        
            }
            DBconnection.closeConnection(connection);
            tblDSMuon.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(docgia.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        txtTimS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTraC = new javax.swing.JTable();
        rbtTS = new javax.swing.JRadioButton();
        rbtTG = new javax.swing.JRadioButton();
        rbtNXB = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDSMuon = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblMadg = new javax.swing.JLabel();
        lblTendg = new javax.swing.JLabel();
        lblMatk = new javax.swing.JLabel();
        lblTentk = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblGt = new javax.swing.JLabel();
        lblNgaysinh = new javax.swing.JLabel();
        lblSdt = new javax.swing.JLabel();
        lblDiachi = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTKDG = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(596, 73));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1307, 576));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel26.setText("Tìm kiếm Sách:");

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton7.setText("Tìm kiếm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txtTimS.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        tblTraC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTraC);

        rbtTS.setText("Theo tên sách");

        rbtTG.setText("Theo tác giả");

        rbtNXB.setText("Theo nhà xuất bản");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(43, 43, 43)
                                .addComponent(txtTimS, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButton7))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(rbtTS)
                                .addGap(54, 54, 54)
                                .addComponent(rbtTG, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(rbtNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtTimS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtTS)
                    .addComponent(rbtTG)
                    .addComponent(rbtNXB))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("TRA CỨU                       ", new javax.swing.ImageIcon(getClass().getResource("/imgicon/research.png")), jPanel1); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("THÔNG TIN SÁCH MƯỢN");

        tblDSMuon.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblDSMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        tblDSMuon.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane2.setViewportView(tblDSMuon);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(" DANH SÁCH MƯỢN     ", new javax.swing.ImageIcon(getClass().getResource("/imgicon/contact-list.png")), jPanel2); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setAutoscrolls(true);
        jPanel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/icons8-password-reset-18.png"))); // NOI18N
        jButton2.setText("Đổi Mật khẩu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Mã độc Giả: ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Tên độc giả:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Mã tài khoản:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Tên tài khoản:");

        lblMadg.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMadg.setForeground(new java.awt.Color(0, 0, 255));
        lblMadg.setText("Mã độc Giả: ");

        lblTendg.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTendg.setForeground(new java.awt.Color(0, 0, 255));
        lblTendg.setText("Tên độc giả:");

        lblMatk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMatk.setForeground(new java.awt.Color(0, 0, 255));
        lblMatk.setText("Mã tài khoản:");

        lblTentk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTentk.setForeground(new java.awt.Color(0, 0, 255));
        lblTentk.setText("Tên tk:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Giới tính:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Ngày sinh:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Số điện thoại:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Địa chỉ");

        lblGt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblGt.setForeground(new java.awt.Color(0, 0, 255));
        lblGt.setText("Giới tính");

        lblNgaysinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNgaysinh.setForeground(new java.awt.Color(0, 0, 255));
        lblNgaysinh.setText("Ngày Sinh:");

        lblSdt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSdt.setForeground(new java.awt.Color(0, 0, 255));
        lblSdt.setText("Sđt:");

        lblDiachi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDiachi.setForeground(new java.awt.Color(0, 0, 255));
        lblDiachi.setText("Địa chỉ:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 112));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Thông Tin Độc Giả");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTendg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMadg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMatk, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(lblTentk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNgaysinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(lblGt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDiachi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSdt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel9)
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblGt)
                        .addGap(50, 50, 50)
                        .addComponent(lblNgaysinh)
                        .addGap(129, 129, 129))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel14)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lblSdt))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblMatk))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblTentk)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblMadg)
                        .addGap(50, 50, 50)
                        .addComponent(lblTendg)
                        .addGap(112, 112, 112)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lblDiachi))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("THÔNG TIN ĐỘC GIẢ ", new javax.swing.ImageIcon(getClass().getResource("/imgicon/icons8-personal-information-64.png")), jPanel4); // NOI18N

        jPanel5.setPreferredSize(new java.awt.Dimension(1307, 167));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/choice.png"))); // NOI18N
        jButton1.setText("Đăng Xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Trường Đại Học Công Nghệ Giao Thông Vận Tải");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Quản Lý Thư Viện");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/logo-utt-border.png"))); // NOI18N

        txtTKDG.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtTKDG.setForeground(new java.awt.Color(255, 51, 51));
        txtTKDG.setText("jLabel1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(182, 182, 182))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(txtTKDG, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTKDG))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1287, Short.MAX_VALUE)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1287, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hienthi(){
        try {
            tblTraC.removeAll();
            String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
            DefaultTableModel model;
            model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .
            
            Connection connection =  DBconnection.geConnection();
            
            String query = "SELECT * FROM Sach";
            java.sql.Statement statement =  connection.createStatement();
	    ResultSet rs = statement.executeQuery(query);
            while(rs.next()) {
                Vector vct = new Vector();
		vct.add(rs.getString("mas"));
                vct.add(rs.getString("tensach"));
                vct.add(rs.getString("matl"));
                vct.add(rs.getString("tacgia"));
                vct.add(rs.getString("nhaxb"));
                vct.add(rs.getString("namxb"));
                vct.add(rs.getString("giasach"));
                vct.add(rs.getString("soluong"));
                vct.add(rs.getString("tomtat"));
                model.addRow(vct);
                tblTraC.setModel(model);
	    }   
        } catch (Exception e) {
        }
        
    
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new dangnhap().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(txtTimS.getText().equals("")){
            try {
                tblTraC.removeAll();
                String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
                DefaultTableModel model;
                model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .

                Connection connection =  DBconnection.geConnection();
                String query = "SELECT * FROM Sach";

                java.sql.Statement statement =  connection.createStatement();
                ResultSet rs = statement.executeQuery(query);
                while(rs.next()) {
                    Vector vct = new Vector();
                    vct.add(rs.getString("mas"));
                    vct.add(rs.getString("tensach"));
                    vct.add(rs.getString("matl"));
                    vct.add(rs.getString("tacgia"));
                    vct.add(rs.getString("nhaxb"));
                    vct.add(rs.getString("namxb"));
                    vct.add(rs.getString("giasach"));
                    vct.add(rs.getString("soluong"));
                    vct.add(rs.getString("tomtat"));
                    model.addRow(vct);
                    tblTraC.setModel(model);
                }
            } catch (Exception e) {
            }
        }
        else{
            if(rbtTS.isSelected()==true){
                try {
                    tblTraC.removeAll();
                    String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
                    DefaultTableModel model;
                    model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .

                    Connection connection =  DBconnection.geConnection();
                    String query = "SELECT * FROM Sach where tensach like N'%"+txtTimS.getText()+"%'";

                    java.sql.Statement statement =  connection.createStatement();
                    ResultSet rs = statement.executeQuery(query);
                    while(rs.next()) {
                        Vector vct = new Vector();
                        vct.add(rs.getString("mas"));
                        vct.add(rs.getString("tensach"));
                        vct.add(rs.getString("matl"));
                        vct.add(rs.getString("tacgia"));
                        vct.add(rs.getString("nhaxb"));
                        vct.add(rs.getString("namxb"));
                        vct.add(rs.getString("giasach"));
                        vct.add(rs.getString("soluong"));
                        vct.add(rs.getString("tomtat"));
                        model.addRow(vct);
                        tblTraC.setModel(model);
                    }
                } catch (Exception e) {
                }
            }else if(rbtNXB.isSelected()==true){
                try {
                    tblTraC.removeAll();
                    String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
                    DefaultTableModel model;
                    model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .

                    Connection connection =  DBconnection.geConnection();
                    String query = "SELECT * FROM Sach where nhaxb like N'%"+txtTimS.getText()+"%'";

                    java.sql.Statement statement =  connection.createStatement();
                    ResultSet rs = statement.executeQuery(query);
                    while(rs.next()) {
                        Vector vct = new Vector();
                        vct.add(rs.getString("mas"));
                        vct.add(rs.getString("tensach"));
                        vct.add(rs.getString("matl"));
                        vct.add(rs.getString("tacgia"));
                        vct.add(rs.getString("nhaxb"));
                        vct.add(rs.getString("namxb"));
                        vct.add(rs.getString("giasach"));
                        vct.add(rs.getString("soluong"));
                        vct.add(rs.getString("tomtat"));
                        model.addRow(vct);
                        tblTraC.setModel(model);
                    }
                } catch (Exception e) {
                }
            }else if(rbtTG.isSelected()==true){
                try {
                    tblTraC.removeAll();
                    String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
                    DefaultTableModel model;
                    model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .

                    Connection connection =  DBconnection.geConnection();
                    String query = "SELECT * FROM Sach where tacgia like N'%"+txtTimS.getText()+"%'";

                    java.sql.Statement statement =  connection.createStatement();
                    ResultSet rs = statement.executeQuery(query);
                    while(rs.next()) {
                        Vector vct = new Vector();
                        vct.add(rs.getString("mas"));
                        vct.add(rs.getString("tensach"));
                        vct.add(rs.getString("matl"));
                        vct.add(rs.getString("tacgia"));
                        vct.add(rs.getString("nhaxb"));
                        vct.add(rs.getString("namxb"));
                        vct.add(rs.getString("giasach"));
                        vct.add(rs.getString("soluong"));
                        vct.add(rs.getString("tomtat"));
                        model.addRow(vct);
                        tblTraC.setModel(model);
                    }
                } catch (Exception e) {
                }
            }

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

          frmDoiMK doiMK = new frmDoiMK();
          doiMK.setVisible(true);
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void showDuLieuDocGia(String matk){
        try {
  
            Connection connection = DBconnection.geConnection();
           
            String query = "select DG.madg, DG.hoten, DG.gioitinh, DG.ngaysinh ,DG.diachi,DG.sdt, TK.taikhoan, TK.matk from DocGia DG inner join TaiKhoan TK on DG.matk = TK.matk and TK.matk = '"+matk+"' ";
            java.sql.Statement statement =  connection.createStatement();
	    ResultSet rs = statement.executeQuery(query);
            while(rs.next()) {
               
		lblMadg.setText(rs.getString(1).trim());
                lblTendg.setText(rs.getString(2).trim());
                lblGt.setText(rs.getString(3).trim());
                lblNgaysinh.setText(rs.getString(4).trim());
                lblDiachi.setText(rs.getString(5).trim());
                lblSdt.setText(rs.getString(6).trim());
                lblTentk.setText(rs.getString(7).trim());
               
                lblMatk.setText(rs.getString(8).trim());
                    
	    }  
            DBconnection.closeConnection(connection);
                
        } catch (SQLException e) {
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(docgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(docgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(docgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(docgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new docgia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDiachi;
    private javax.swing.JLabel lblGt;
    private javax.swing.JLabel lblMadg;
    private javax.swing.JLabel lblMatk;
    private javax.swing.JLabel lblNgaysinh;
    private javax.swing.JLabel lblSdt;
    private javax.swing.JLabel lblTendg;
    private javax.swing.JLabel lblTentk;
    private javax.swing.JRadioButton rbtNXB;
    private javax.swing.JRadioButton rbtTG;
    private javax.swing.JRadioButton rbtTS;
    private javax.swing.JTable tblDSMuon;
    private javax.swing.JTable tblTraC;
    private javax.swing.JLabel txtTKDG;
    private javax.swing.JTextField txtTimS;
    // End of variables declaration//GEN-END:variables
}
