/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giaodien;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nvcam
 */
public class frmqlphieumuon extends javax.swing.JFrame {

    /**
     * Creates new form frmqlphieumuon
     */
    public frmqlphieumuon() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        hienthi1();
        hienthi();
        status ="Reset";
        Dieukhien(status);
    }
    public void ReLoad() {
        this.setVisible(true);
        hienthi1();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbpmdadangky = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        txtmasach = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txttinhtrangsach = new javax.swing.JComboBox<>();
        bthuy = new javax.swing.JButton();
        btluu = new javax.swing.JButton();
        btlammoi = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbhoadon = new javax.swing.JTable();
        jLabel49 = new javax.swing.JLabel();
        txtngaytrathuc = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        txtmaphieumuon = new javax.swing.JTextField();
        txtmahoadon = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtsongaymuon = new javax.swing.JTextField();
        txtngaymuon = new com.toedter.calendar.JDateChooser();
        them = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtsoluongmuon = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTabbedPane3.setPreferredSize(new java.awt.Dimension(1307, 756));
        jTabbedPane3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPane3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 112));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("CÁC PHIẾU MƯỢN ĐÃ ĐĂNG KÝ");

        tbpmdadangky.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbpmdadangky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpmdadangkyMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbpmdadangky);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/them.png"))); // NOI18N
        jButton6.setText("Thêm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/icon_previous.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(1028, 1028, 1028)
                        .addComponent(jButton6))
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22))
        );

        jTabbedPane3.addTab("Quản Lý Phiếu Mượn", jPanel11);

        jPanel12.setBackground(new java.awt.Color(153, 204, 255));

        txtmasach.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtmasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmasachActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel19.setText("Mã phiếu mượn:");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel20.setText("Mã sách:");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel21.setText("Ngày trả thực:");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel22.setText("Tình trạng sách:");

        txttinhtrangsach.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txttinhtrangsach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bình thường", "Mất", "Hư Hỏng" }));

        bthuy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bthuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/remove (1).png"))); // NOI18N
        bthuy.setText("Hủy");
        bthuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthuyActionPerformed(evt);
            }
        });

        btluu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btluu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/luu.png"))); // NOI18N
        btluu.setText("Lưu");
        btluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btluuActionPerformed(evt);
            }
        });

        btlammoi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btlammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/lammoi.png"))); // NOI18N
        btlammoi.setText("Làm mới");
        btlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlammoiActionPerformed(evt);
            }
        });

        tbhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbhoadonMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbhoadon);

        jLabel49.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel49.setText("Mã hóa đơn:");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel23.setText("Ngày mượn:");

        txtmaphieumuon.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        txtmahoadon.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtmahoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmahoadonActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel24.setText("Số ngày được mượn:");

        txtsongaymuon.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtsongaymuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsongaymuonActionPerformed(evt);
            }
        });

        them.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/plus.png"))); // NOI18N
        them.setText("Sửa thông tin");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel4.setText("Nếu Sách quá hạn, thì tiền mượn là số ngày quá hạn * 5000đ");

        jLabel3.setText("Nếu Sách bị hư hỏng tiền phạt là 50.000đ");

        jLabel2.setText("Nếu Sách bị mất tiền phạt là 100.000đ");

        jLabel1.setText("* chú ý : Nếu Sách bình thường, thì tiền mượn là 5.000đ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel25.setText("Số lượng mượn:");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel26.setText("Số lượng mượn:");

        txtsoluongmuon.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtsoluongmuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoluongmuonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addContainerGap(50, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtmasach, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmaphieumuon, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(153, 153, 153)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtngaytrathuc, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttinhtrangsach, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtsoluongmuon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtsongaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(them))
                                .addGap(134, 134, 134)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(btluu)
                                        .addGap(58, 58, 58)
                                        .addComponent(bthuy)
                                        .addGap(251, 251, 251)
                                        .addComponent(btlammoi))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(txtmahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttinhtrangsach))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngaytrathuc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmaphieumuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsoluongmuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsongaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them)
                    .addComponent(btluu)
                    .addComponent(bthuy)
                    .addComponent(btlammoi))
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jTabbedPane3.addTab("Quản Lý Trả", jPanel12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1307, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getSLMuon(String ms){
        String sql = "SELECT soluongmuon  FROM Sach WHERE mas = '" + ms + "'";
        Connection connection =DBconnection.geConnection();
        try{
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                return rs.getInt("soluongmuon");
            }
        }catch(Exception e){

        }
        return 0;
    }
    public int getSoNgayTra(String maPM, String maS, String ngayTra) {
        String sql = "select ((DAY('"+ngayTra+"') - DAY(pm.ngaymuon)) - pm.songaymuon) as 'S' from HoaDon hd , PhieuMuon pm where hd.mapm = pm.mapm and ((DAY('"+ngayTra+"') - DAY(pm.ngaymuon)) > pm.songaymuon) and pm.mapm like '%"+maPM+"%' and pm.mas like '%"+maS+"%'";
        Connection connection =DBconnection.geConnection();
        try{
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                return rs.getInt("S");
              
            }
        }catch(Exception e){
            System.out.println("khong tinh dc");
        }
        return 0;
    }
    private void loadMaS(String name) {
        String sql = "SELECT mas FROM Sach WHERE tensach like N'%" + name + "%'";
        Connection connection =DBconnection.geConnection();
        try{
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                this.txtmasach.setText(rs.getString("mas"));
            }
        }catch(Exception e){

        }
        
    }
    private static String status ="";
    private void Dieukhien(String status){
    if(status.equals("Reset"))
    {
        txtmaphieumuon.setEnabled(false);
        txtmasach.setEnabled(false);
        txtsoluongmuon.setEnabled(false);
        txtngaymuon.setEnabled(false);
        txtsongaymuon.setEnabled(false);
        txtngaytrathuc.setEnabled(false);
        txttinhtrangsach.setEnabled(false);
        btluu.setEnabled(false);
        btlammoi.setEnabled(false);
        bthuy.setEnabled(false);
     //   btsua1.setEnabled(true);
        txtmahoadon.setEnabled(false);
        
        
    }
    
    else if(status.equals("Them"))
    {
        txtmaphieumuon.setEnabled(false);
        txtmasach.setEnabled(false);
        txtngaymuon.setEnabled(false);
        txtsongaymuon.setEnabled(false);
        txtngaytrathuc.setEnabled(true);
        txttinhtrangsach.setEnabled(true);
        btluu.setEnabled(true);
        btlammoi.setEnabled(true);
        bthuy.setEnabled(true);
       // btsua1.setEnabled(false);
        txtmahoadon.setEnabled(false);
        txtmahoadon.requestFocus();
    }
}
    private void hienthi(){
        try {
            tbhoadon.removeAll();
            String [] arr = {"Mã hóa đơn ","Mã phiếu mượn","Mã sách","Số lượng","Ngày Mượn","Số ngày được mượn","Ngày trả thực","Tình trạng","Thành tiền",};
            DefaultTableModel model;
            model = new DefaultTableModel(arr, 0);

            Connection connection =DBconnection.geConnection();

            String query = "select HD.mahd, HD.mapm, PM.mas, PM.soluong, PM.ngaymuon, PM.songaymuon, HD.ngaytra, HD.trangthai, HD.thanhtien from HoaDon HD inner join Phieumuon PM on HD.mapm = PM.mapm  where HD.mapm = '"+txtmaphieumuon.getText()+"'";
            Statement statement =  connection.createStatement();
            ResultSet rs = statement.executeQuery(query);
            while(rs.next()) {
                Vector vct = new Vector();
                vct.add(rs.getString("mahd"));
                vct.add(rs.getString("mapm"));
                vct.add(rs.getString("mas"));
                vct.add(rs.getString("soluong"));
                vct.add(rs.getString("ngaymuon"));
                vct.add(rs.getString("songaymuon"));
                vct.add(rs.getString("ngaytra"));
                vct.add(rs.getString("trangthai"));
                vct.add(rs.getInt("thanhtien"));
               
                model.addRow(vct);
                }
            DBconnection.closeConnection(connection);
            tbhoadon.setModel(model);
        } catch (Exception e) {
        }
    }
    private void hienthi1(){
        try {
            tbpmdadangky.removeAll();
            String [] arr = {"Mã phiếu mượn ","Mã độc giả","Tên độc giả ","Tên Sách ","Số lượng ","Ngày mượn","Số ngày mượn", "Ghi chú","Trạng Thái "};
            DefaultTableModel model;
            model = new DefaultTableModel(arr, 0);

            Connection connection =DBconnection.geConnection();

            String query = "select PM.mapm,DG.madg , DG.hoten, S.tensach, PM.soluong, PM.ngaymuon, PM.songaymuon, PM.ghichu, PM.trangthai from DocGia DG inner join Phieumuon PM on DG.madg = PM.madg inner join Sach S on PM.mas = S.mas ";
            Statement statement =  connection.createStatement();
            ResultSet rs = statement.executeQuery(query);
            while(rs.next()) {
                Vector vct = new Vector();
                vct.add(rs.getString("mapm"));
                vct.add(rs.getString("madg"));
                vct.add(rs.getString("hoten"));
                vct.add(rs.getString("tensach"));
                vct.add(rs.getString("soluong"));
                vct.add(rs.getString("ngaymuon"));
                vct.add(rs.getInt("songaymuon"));
                vct.add(rs.getString("ghichu"));
                vct.add(rs.getString("trangthai"));
 
                model.addRow(vct);        
            }
            DBconnection.closeConnection(connection);
            tbpmdadangky.setModel(model);
            
        } catch (Exception e) {
    }
}
 
    private void tbpmdadangkyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpmdadangkyMouseClicked
        jTabbedPane3.setSelectedIndex(1);

        DefaultTableModel model = (DefaultTableModel)tbpmdadangky.getModel();
        int row = tbpmdadangky.getSelectedRow();

        String mapm = tbpmdadangky.getValueAt(row, 0).toString();
        String tensach = tbpmdadangky.getValueAt(row, 3).toString();
        String soluongmuon = tbpmdadangky.getValueAt(row, 4).toString();
        Date ngaymuon = null;
        try {
            ngaymuon = (Date) new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(row, 5).toString());
        } catch (ParseException ex) {
            Logger.getLogger(frmqlphieumuon.class.getName()).log(Level.SEVERE, null, ex);
        }
        String songaymuon = tbpmdadangky.getValueAt(row, 6).toString();

        String trangthai = tbpmdadangky.getValueAt(row, 8).toString();

        txtmaphieumuon.setText(mapm);
        txtngaymuon.setDate(ngaymuon);  
        loadMaS(tensach);
        txtsoluongmuon.setText(soluongmuon);
        txtsongaymuon.setText(songaymuon);

        if (trangthai.equals("Chưa trả")) {
            try {
                Connection conn = DBconnection.geConnection();
                if (conn != null) {
                    //  System.out.println("Connected");

                }
                String sql = "insert into HoaDon(mapm) values( '"+txtmaphieumuon.getText()+"') ";
                java.sql.Statement stm=  conn.createStatement();
                int i = stm.executeUpdate(sql);
                if(i>0)
                {
                    System.out.println("Thêm thành công");
                    hienthi(); 
                }
                else
                {
                    System.out.println("Thêm thất bại");
                }
            } catch (SQLException ex) {
                System.err.println("Cannot connect database, " + ex);
            }
        }

    }//GEN-LAST:event_tbpmdadangkyMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        phieumuon fpm= new phieumuon();
        fpm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void bthuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthuyActionPerformed
        // TODO add your handling code here:
        status = "Reset";
        Dieukhien(status);
    }//GEN-LAST:event_bthuyActionPerformed

    private void btluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btluuActionPerformed
        if (status.equals("Them")){

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String ngaytra = sdf.format(txtngaytrathuc.getDate());
            System.out.println("songaytra"+ngaytra);
            String trangthai = (String) txttinhtrangsach.getSelectedItem();
            int songayTra = getSoNgayTra(txtmaphieumuon.getText(),txtmasach.getText(),ngaytra );
            System.out.println("songaytra"+songayTra);
            int thanhtien = 0;
            if(trangthai.equalsIgnoreCase("Bình thường")){
                thanhtien = 5000+5000*songayTra;    
            }else if(trangthai.equalsIgnoreCase("Mất")){
                thanhtien = 100000;
            }else{
                thanhtien = 50000+5000*songayTra;
            }
            try {
//                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//                String date = sdf.format(txtngaytrathuc.getDate());

                Connection conn = DBconnection.geConnection();
                if (conn != null) {
                    //  System.out.println("Connected");

                }
                String sql = "Update HoaDon set trangthai = N'"+txttinhtrangsach.getSelectedItem()+"',ngaytra = '"+ngaytra+"',thanhtien = '"+thanhtien+"'Where mahd = '"+txtmahoadon.getText()+"' ";
                Statement stm=  conn.createStatement();
                int i = stm.executeUpdate(sql);
                if(i>0)
                {
                    System.out.println("Sửa thành công");                    
                    hienthi1();
                    status="Reset";
                    Dieukhien(status);
                try {
                
                String sqlpm = "Update PhieuMuon set trangthai = N'Đã trả' where mapm = '"+txtmaphieumuon.getText()+"'";
                
                int a = stm.executeUpdate(sqlpm);
                if(a>0)
                {
                    System.out.println("update đã trả thành công");   
                    hienthi();  
                }
                else
                {
                    System.out.println("sửa thất bại");
                }
                int slmuon = getSLMuon(txtmasach.getText()) - Integer.parseInt(txtsoluongmuon.getText());
                String sqlslm = "Update Sach set soluongmuon = '"+slmuon+"' where mas = '"+txtmasach.getText()+"'";
                
                int slm = stm.executeUpdate(sqlslm);
                if(slm>0)
                {
                    System.out.println("sửa slm thành công");
                    hienthi(); 
                    hienthi1();
                }
                else
                {
                    System.out.println("sửa thất bại");
                }
                } catch (SQLException ex) {
                    System.err.println("Cannot connect database, " + ex);
                }    
                }
                else
                {
                    System.out.println("Sửa thất bại");
                }
            } catch (SQLException ex) {
                System.err.println("Cannot connect database, " + ex);
            }

        }
    }//GEN-LAST:event_btluuActionPerformed

    private void btlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlammoiActionPerformed
 
    txtmahoadon.setText("");
    txttinhtrangsach.setSelectedIndex(0);
          
    }//GEN-LAST:event_btlammoiActionPerformed

    private void tbhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbhoadonMouseClicked
           
            DefaultTableModel model = (DefaultTableModel)tbhoadon.getModel();
            int row = tbhoadon.getSelectedRow();
            //String mas = phieumuontrai.getValueAt(row,0).toString();
            String  mahd = tbhoadon.getValueAt(row, 0).toString();  
            txtmahoadon.setText(mahd);       
    }//GEN-LAST:event_tbhoadonMouseClicked

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        status = "Them";
        Dieukhien(status);

    }//GEN-LAST:event_themActionPerformed

    private void txtsongaymuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsongaymuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsongaymuonActionPerformed

    private void txtmahoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmahoadonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmahoadonActionPerformed

    private void jTabbedPane3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane3AncestorAdded
       hienthi1();
    }//GEN-LAST:event_jTabbedPane3AncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        trangchuthuvien ftv = new trangchuthuvien();
        ftv.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtmasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmasachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmasachActionPerformed

    private void txtsoluongmuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoluongmuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsoluongmuonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmqlphieumuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmqlphieumuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmqlphieumuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmqlphieumuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmqlphieumuon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthuy;
    private javax.swing.JButton btlammoi;
    private javax.swing.JButton btluu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable tbhoadon;
    private javax.swing.JTable tbpmdadangky;
    private javax.swing.JButton them;
    private javax.swing.JTextField txtmahoadon;
    private javax.swing.JTextField txtmaphieumuon;
    private javax.swing.JTextField txtmasach;
    private com.toedter.calendar.JDateChooser txtngaymuon;
    private com.toedter.calendar.JDateChooser txtngaytrathuc;
    private javax.swing.JTextField txtsoluongmuon;
    private javax.swing.JTextField txtsongaymuon;
    private javax.swing.JComboBox<String> txttinhtrangsach;
    // End of variables declaration//GEN-END:variables
}
