/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giaodien;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nvcam
 */
public class phieumuon extends javax.swing.JFrame {

    /**
     * Creates new form phieumuon
     */
    public phieumuon() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        hienthi();
        status = "Reset";
        Dieukhien(status);
        loadCB();
        loadDG();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        maphieumuon1 = new javax.swing.JTextField();
        ghichu1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        songaymuon1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        soluong1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        trangthai1 = new javax.swing.JComboBox<>();
        ngaymuon1 = new com.toedter.calendar.JDateChooser();
        masach1 = new javax.swing.JComboBox<>();
        madocgia1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lammoi = new javax.swing.JButton();
        them = new javax.swing.JButton();
        sua = new javax.swing.JButton();
        luu = new javax.swing.JButton();
        huy1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        phieumuontrai = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1307, 756));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/icon_previous.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 112));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/bill.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ PHIẾU MƯỢN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(405, 405, 405)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Mã phiếu mượn:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Số ngày mượn:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Ghi chú:");

        maphieumuon1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        maphieumuon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maphieumuon1ActionPerformed(evt);
            }
        });

        ghichu1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Mã độc giả:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Ngày mượn:");

        songaymuon1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        songaymuon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songaymuon1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Mã Sách:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Số Lượng:");

        soluong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soluong1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Trạng Thái:");

        trangthai1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        trangthai1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa trả", "Đã trả" }));
        trangthai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trangthai1ActionPerformed(evt);
            }
        });

        ngaymuon1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        masach1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        madocgia1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        lammoi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/lammoi.png"))); // NOI18N
        lammoi.setText("Làm mới");
        lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lammoiActionPerformed(evt);
            }
        });

        them.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/plus.png"))); // NOI18N
        them.setText(" Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        sua.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/exchange1.png"))); // NOI18N
        sua.setText("  Sửa");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        luu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/luu.png"))); // NOI18N
        luu.setText("Lưu");
        luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuActionPerformed(evt);
            }
        });

        huy1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        huy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/remove (1).png"))); // NOI18N
        huy1.setText("  Hủy");
        huy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huy1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sua, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huy1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luu, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(lammoi)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(them)
                .addGap(18, 18, 18)
                .addComponent(sua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(luu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huy1)
                    .addComponent(lammoi))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maphieumuon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(songaymuon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trangthai1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(112, 112, 112)
                        .addComponent(ghichu1)))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(soluong1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ngaymuon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(masach1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(madocgia1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(madocgia1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(maphieumuon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(songaymuon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(ghichu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ngaymuon1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(masach1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(soluong1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trangthai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        phieumuontrai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        phieumuontrai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phieumuontraiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(phieumuontrai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadCB() 
    {
        Connection conn = DBconnection.geConnection();
        String sql ="select * from Sach";
        try {
            java.sql.PreparedStatement stm= conn.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            while (rs.next()) {
              this.masach1.addItem(rs.getString("mas"));
                
            }
        } catch (SQLException ex) {
           // Logger.getLogger(pane2.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }
    public void loadDG() 
    {
        Connection conn = DBconnection.geConnection();
        String sql ="select madg from DocGia";
        try {
            java.sql.PreparedStatement stm= conn.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            while (rs.next()) {
              this.madocgia1.addItem(rs.getString("madg"));
                
            }
        } catch (SQLException ex) {
           // Logger.getLogger(pane2.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }
    public int getSLSach(String ms){
        String sql = "SELECT soluong  FROM Sach WHERE mas = '" + ms + "'";
        Connection connection =DBconnection.geConnection();
        try{
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                return rs.getInt("soluong");
            }
        }catch(Exception e){

        }
        return 0;
    }
    public int getSLMuon(String ms){
        String sql = "SELECT soluongmuon  FROM Sach WHERE mas = '" + ms + "'";
        Connection connection =DBconnection.geConnection();
        try{
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                return rs.getInt("soluongmuon");
            }
        }catch(Exception e){

        }
        return 0;
    }
    private void loadMaS(String name) {
        String sql = "SELECT mas FROM Sach WHERE tensach like N'%" + name + "%'";
        Connection connection =DBconnection.geConnection();
        try{
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                this.masach1.setSelectedItem(rs.getString("mas"));
            }
        }catch(Exception e){

        }
        
    }
    private static String status ="";
    private void Dieukhien(String status){
    if(status.equals("Reset"))
    {
        maphieumuon1.setEnabled(false);
        madocgia1.setEnabled(false);
        ngaymuon1.setEnabled(false);
        songaymuon1.setEnabled(false);
        ghichu1.setEnabled(false);
        trangthai1.setEnabled(false);
        luu.setEnabled(false);
        lammoi.setEnabled(false);
        sua.setEnabled(true);
        them.setEnabled(true);
        masach1.setEnabled(false);
        soluong1.setEnabled(false);
        huy1.setEnabled(false);
    }
    else if(status.equals("them")){
        maphieumuon1.setEnabled(false);
        madocgia1.setEnabled(true);
        ngaymuon1.setEnabled(true);
        songaymuon1.setEnabled(true);
        ghichu1.setEnabled(true);
        trangthai1.setEnabled(false);
        trangthai1.setSelectedIndex(0);
        luu.setEnabled(true);
        lammoi.setEnabled(true);
        sua.setEnabled(false);
        them.setEnabled(false);
        masach1.setEnabled(true);
        soluong1.setEnabled(true);
        huy1.setEnabled(true);
        
    }
    else if(status.equals("sua"))
    {
        maphieumuon1.setEnabled(false);
        madocgia1.setEnabled(false);
        ngaymuon1.setEnabled(true);
        songaymuon1.setEnabled(true);
        ghichu1.setEnabled(true);
        trangthai1.setEnabled(false);
        luu.setEnabled(true);
        lammoi.setEnabled(true);
        sua.setEnabled(false);
        them.setEnabled(false);
        masach1.setEnabled(true);
        soluong1.setEnabled(true);
        huy1.setEnabled(true);
        maphieumuon1.requestFocus();
    }
}
    private void hienthi(){
        try {
            phieumuontrai.removeAll();
            String [] arr = {"Mã phiếu mượn ","Mã độc giả","Tên độc giả ","Tên Sách ","Số lượng ","Ngày mượn","Số ngày mượn", "Ghi chú","Trạng Thái "};
            DefaultTableModel model;
            model = new DefaultTableModel(arr, 0);

            Connection connection =DBconnection.geConnection();

            String query = "select PM.mapm,DG.madg , DG.hoten, S.tensach, PM.soluong, PM.ngaymuon, PM.songaymuon, PM.ghichu, PM.trangthai from DocGia DG inner join Phieumuon PM on DG.madg = PM.madg inner join Sach S on PM.mas = S.mas  ";
            Statement statement =  connection.createStatement();
            ResultSet rs = statement.executeQuery(query);
            while(rs.next()) {
                Vector vct = new Vector();
                vct.add(rs.getString("mapm"));
                vct.add(rs.getString("madg"));
                vct.add(rs.getString("hoten"));
                vct.add(rs.getString("tensach"));
                vct.add(rs.getString("soluong"));
                vct.add(rs.getString("ngaymuon"));
                vct.add(rs.getString("songaymuon"));
                vct.add(rs.getString("ghichu"));
                vct.add(rs.getString("trangthai"));
 
                model.addRow(vct);        
            }
            DBconnection.closeConnection(connection);
            phieumuontrai.setModel(model);
            
        } catch (Exception e) {
    }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        frmqlphieumuon fpm = new frmqlphieumuon();
        fpm.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        status = "them";
        Dieukhien(status);
    }//GEN-LAST:event_themActionPerformed

    private void lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lammoiActionPerformed
        // TODO add your handling code here:
        maphieumuon1.setText("");
       
        songaymuon1.setText("");
        ghichu1.setText("");
        soluong1.setText("");
        masach1.setSelectedItem("");
    }//GEN-LAST:event_lammoiActionPerformed

    private void luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if( songaymuon1.getText().equals("")){
                sb.append("Bạn chưa nhập số ngày mượn\n");
                songaymuon1.requestFocus();
            }
            if(soluong1.getText().equals("")){
                sb.append("bạn chưa nhập số lượng\n");
                soluong1.requestFocus();
         
            }
            if (sb.length()>0) {
                JOptionPane.showMessageDialog(this, sb.toString());
                return;
            }
        if(status.equals("them"))
        {
            Connection con = DBconnection.geConnection();
                int slmuon = Integer.parseInt(soluong1.getText()) + getSLMuon((String) masach1.getSelectedItem());
 
                if( slmuon > getSLSach((String) masach1.getSelectedItem()) ){
                    JOptionPane.showMessageDialog(this, "Số lượng sách mượn vượt quá trong kho");
                }
                else{
                    try {
                        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                        String date = sdf.format(ngaymuon1.getDate());

                        Connection conn = DBconnection.geConnection();
                        if (conn != null) {
                            //  System.out.println("Connected");

                        }
                        String sql = "insert into PhieuMuon(madg,ngaymuon, songaymuon, ghichu, trangthai, mas, soluong) values( '"+madocgia1.getSelectedItem()+"', '"+date+"', '"+songaymuon1.getText()+"', N'"+ghichu1.getText()+"', N'"+trangthai1.getSelectedItem()+"','"+masach1.getSelectedItem()+"','"+soluong1.getText()+"')";
                        java.sql.Statement stm=  conn.createStatement();
                        int i = stm.executeUpdate(sql);
                        
                        String sqlsoluongmuon = "Update Sach set soluongmuon ='"+slmuon+"' where mas = '"+masach1.getSelectedItem()+"'";
                        Statement stmm=  conn.createStatement();
                        int j = stmm.executeUpdate(sqlsoluongmuon);
                        if(i>0 && j > 0)
                        {

                            System.out.println("Thêm thành công");
                            System.out.println("cap nhat thanh cong");
                            hienthi();
                            status="Reset";
                            Dieukhien(status);
                        }
                        else
                        {
                            System.out.println("Thêm thất bại");
                        }
                        
                    } catch (SQLException ex) {
                        System.err.println("Cannot connect database, " + ex);
                    }
                }

        }else if (status.equals("sua")){
            if(trangthai1.getSelectedItem().equals("Đã trả")){
                JOptionPane.showMessageDialog(this, "không thể sửa phiếu đã trả");
            }else{
                try {
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String date = sdf.format(ngaymuon1.getDate());

                    Connection conn = DBconnection.geConnection();
                    String sql = "Update PhieuMuon set ngaymuon = '"+date+"',songaymuon = '"+songaymuon1.getText()+"',ghichu = N'"+ghichu1.getText()+"',trangthai = N'"+trangthai1.getSelectedItem()+"',mas ='"+masach1.getSelectedItem()+"',soluong ='"+soluong1.getText()+"' where mapm = '"+maphieumuon1.getText()+"'";
                    Statement stm=  conn.createStatement();
                    int i = stm.executeUpdate(sql);
                    if(i>0)
                    {

                        System.out.println("sửa thành công");
                        hienthi();
                        status="Reset";
                        Dieukhien(status);
                    }
                    else
                    {
                        System.out.println("sửa thất bại");
                    }
                } catch (SQLException ex) {
                    System.err.println("Cannot connect database, " + ex);
                }
            }
        }
    }//GEN-LAST:event_luuActionPerformed

    private void maphieumuon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maphieumuon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maphieumuon1ActionPerformed

    private void huy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huy1ActionPerformed
        // TODO add your handling code here:
        status = "Reset";
        Dieukhien(status);
    }//GEN-LAST:event_huy1ActionPerformed

    private void songaymuon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songaymuon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songaymuon1ActionPerformed

    private void soluong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soluong1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soluong1ActionPerformed

    private void phieumuontraiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phieumuontraiMouseClicked
        try {
            
            DefaultTableModel model = (DefaultTableModel)phieumuontrai.getModel();
            int row = phieumuontrai.getSelectedRow();
      
            String  mapm = phieumuontrai.getValueAt(row, 0).toString();
            String madg = phieumuontrai.getValueAt(row, 1).toString();
            String tensach = phieumuontrai.getValueAt(row, 3).toString();
            String  soluong = phieumuontrai.getValueAt(row, 4).toString();
            Date ngaymuon = (Date) new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(row, 5).toString());
            String  songaymuon = phieumuontrai.getValueAt(row, 6).toString();
            String  ghichu = phieumuontrai.getValueAt(row, 7).toString();
            String  trangthai = phieumuontrai.getValueAt(row, 8).toString();
            
            maphieumuon1.setText(mapm);
            madocgia1.setSelectedItem(madg);
            ngaymuon1.setDate(ngaymuon);
            songaymuon1.setText(songaymuon);
            ghichu1.setText(ghichu);
            trangthai1.setSelectedItem(trangthai);
            soluong1.setText(soluong);
            loadMaS(tensach);
            
        } catch (ParseException ex) {
            Logger.getLogger(phieumuon.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_phieumuontraiMouseClicked

    private void trangthai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trangthai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trangthai1ActionPerformed

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
        status = "sua";
        Dieukhien(status);
    }//GEN-LAST:event_suaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(phieumuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(phieumuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(phieumuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(phieumuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new phieumuon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField ghichu1;
    private javax.swing.JButton huy1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lammoi;
    private javax.swing.JButton luu;
    private javax.swing.JComboBox<String> madocgia1;
    private javax.swing.JTextField maphieumuon1;
    private javax.swing.JComboBox<String> masach1;
    private com.toedter.calendar.JDateChooser ngaymuon1;
    private javax.swing.JTable phieumuontrai;
    private javax.swing.JTextField soluong1;
    private javax.swing.JTextField songaymuon1;
    private javax.swing.JButton sua;
    private javax.swing.JButton them;
    private javax.swing.JComboBox<String> trangthai1;
    // End of variables declaration//GEN-END:variables
}
