/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaodien;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class tracuuDG extends javax.swing.JFrame {

    /**
     * Creates new form tracuuDG
     */
    public tracuuDG() {
        initComponents();
        hienthi();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        txtTimS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTraC = new javax.swing.JTable();
        rbtTS = new javax.swing.JRadioButton();
        rbtTG = new javax.swing.JRadioButton();
        rbtNXB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel26.setText("Tìm kiếm Sách:");

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton7.setText("Tìm kiếm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txtTimS.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        tblTraC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTraC);

        rbtTS.setText("Theo tên sách");

        rbtTG.setText("Theo tác giả");

        rbtNXB.setText("Theo nhà xuất bản");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel26)
                        .addGap(43, 43, 43)
                        .addComponent(txtTimS, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton7))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(rbtTS)
                        .addGap(54, 54, 54)
                        .addComponent(rbtTG, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(rbtNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtTimS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtTS)
                    .addComponent(rbtTG)
                    .addComponent(rbtNXB))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(txtTimS.getText().equals("")){
         try {
            tblTraC.removeAll();
            String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
            DefaultTableModel model;
            model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .
            
            Connection connection =  DBconnection.geConnection();
             String query = "SELECT * FROM Sach";
           
            java.sql.Statement statement =  connection.createStatement();
	    ResultSet rs = statement.executeQuery(query);
            while(rs.next()) {
                Vector vct = new Vector();
		vct.add(rs.getString("mas"));
                vct.add(rs.getString("tensach"));
                vct.add(rs.getString("matl"));
                vct.add(rs.getString("tacgia"));
                vct.add(rs.getString("nhaxb"));
                vct.add(rs.getString("namxb"));
                vct.add(rs.getString("giasach"));
                vct.add(rs.getString("soluong"));
                vct.add(rs.getString("tomtat"));
                model.addRow(vct);
                tblTraC.setModel(model);
	    }   
        } catch (Exception e) {
        }
        }
        else{
            if(rbtTS.isSelected()==true){
                try {
            tblTraC.removeAll();
            String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
            DefaultTableModel model;
            model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .
            
            Connection connection =  DBconnection.geConnection();
             String query = "SELECT * FROM Sach where tensach like N'%"+txtTimS.getText()+"%'";
           
            java.sql.Statement statement =  connection.createStatement();
	    ResultSet rs = statement.executeQuery(query);
            while(rs.next()) {
                Vector vct = new Vector();
		vct.add(rs.getString("mas"));
                vct.add(rs.getString("tensach"));
                vct.add(rs.getString("matl"));
                vct.add(rs.getString("tacgia"));
                vct.add(rs.getString("nhaxb"));
                vct.add(rs.getString("namxb"));
                vct.add(rs.getString("giasach"));
                vct.add(rs.getString("soluong"));
                vct.add(rs.getString("tomtat"));
                model.addRow(vct);
                tblTraC.setModel(model);
	    }   
        } catch (Exception e) {
        } 
            }else if(rbtNXB.isSelected()==true){
                 try {
            tblTraC.removeAll();
            String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
            DefaultTableModel model;
            model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .
            
            Connection connection =  DBconnection.geConnection();
             String query = "SELECT * FROM Sach where nhaxb like N'%"+txtTimS.getText()+"%'";
           
            java.sql.Statement statement =  connection.createStatement();
	    ResultSet rs = statement.executeQuery(query);
            while(rs.next()) {
                Vector vct = new Vector();
		vct.add(rs.getString("mas"));
                vct.add(rs.getString("tensach"));
                vct.add(rs.getString("matl"));
                vct.add(rs.getString("tacgia"));
                vct.add(rs.getString("nhaxb"));
                vct.add(rs.getString("namxb"));
                vct.add(rs.getString("giasach"));
                vct.add(rs.getString("soluong"));
                vct.add(rs.getString("tomtat"));
                model.addRow(vct);
                tblTraC.setModel(model);
	    }   
        } catch (Exception e) {
        }
            }else if(rbtTG.isSelected()==true){
                try {
            tblTraC.removeAll();
            String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
            DefaultTableModel model;
            model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .
            
            Connection connection =  DBconnection.geConnection();
             String query = "SELECT * FROM Sach where tacgia like N'%"+txtTimS.getText()+"%'";
           
            java.sql.Statement statement =  connection.createStatement();
	    ResultSet rs = statement.executeQuery(query);
            while(rs.next()) {
                Vector vct = new Vector();
		vct.add(rs.getString("mas"));
                vct.add(rs.getString("tensach"));
                vct.add(rs.getString("matl"));
                vct.add(rs.getString("tacgia"));
                vct.add(rs.getString("nhaxb"));
                vct.add(rs.getString("namxb"));
                vct.add(rs.getString("giasach"));
                vct.add(rs.getString("soluong"));
                vct.add(rs.getString("tomtat"));
                model.addRow(vct);
                tblTraC.setModel(model);
	    }   
        } catch (Exception e) {
        } 
            }
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed
private void hienthi(){
        try {
            tblTraC.removeAll();
            String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
            DefaultTableModel model;
            model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .
            
            Connection connection =  DBconnection.geConnection();
            
            String query = "SELECT * FROM Sach";
            java.sql.Statement statement =  connection.createStatement();
	    ResultSet rs = statement.executeQuery(query);
            while(rs.next()) {
                Vector vct = new Vector();
		vct.add(rs.getString("mas"));
                vct.add(rs.getString("tensach"));
                vct.add(rs.getString("matl"));
                vct.add(rs.getString("tacgia"));
                vct.add(rs.getString("nhaxb"));
                vct.add(rs.getString("namxb"));
                vct.add(rs.getString("giasach"));
                vct.add(rs.getString("soluong"));
                vct.add(rs.getString("tomtat"));
                model.addRow(vct);
                tblTraC.setModel(model);
	    }   
        } catch (Exception e) {
        }
        
    
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tracuuDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tracuuDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tracuuDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tracuuDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tracuuDG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtNXB;
    private javax.swing.JRadioButton rbtTG;
    private javax.swing.JRadioButton rbtTS;
    private javax.swing.JTable tblTraC;
    private javax.swing.JTextField txtTimS;
    // End of variables declaration//GEN-END:variables
}
