/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giaodien;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nvcam
 */
public class trangchuthuvien extends javax.swing.JFrame {

    
    /**
     * Creates new form trangchuthuvien
     */
    public trangchuthuvien() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        hienthi();
        
    }
        private void hienthi(){
        try {
            tblTraC.removeAll();
            String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
            DefaultTableModel model;
            model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .
            
            Connection connection =  DBconnection.geConnection();
            
            String query = "SELECT * FROM Sach";
            java.sql.Statement statement =  connection.createStatement();
	    ResultSet rs = statement.executeQuery(query);
            while(rs.next()) {
                Vector vct = new Vector();
		vct.add(rs.getString("mas"));
                vct.add(rs.getString("tensach"));
                vct.add(rs.getString("matl"));
                vct.add(rs.getString("tacgia"));
                vct.add(rs.getString("nhaxb"));
                vct.add(rs.getString("namxb"));
                vct.add(rs.getString("giasach"));
                vct.add(rs.getString("soluong"));
                vct.add(rs.getString("tomtat"));
                model.addRow(vct);
                tblTraC.setModel(model);
	    }   
        } catch (Exception e) {
        }
        
    
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        txtTimS = new javax.swing.JTextField();
        rbtTS = new javax.swing.JRadioButton();
        rbtTG = new javax.swing.JRadioButton();
        rbtNXB = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTraC = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_dangxuat = new javax.swing.JMenuItem();
        menu_thoat = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        munu_qltt = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 174, 118));

        jPanel5.setPreferredSize(new java.awt.Dimension(1303, 137));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Trường Đại Học Công Nghệ Giao Thông Vận Tải");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Quản Lý Thư Viện");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/logo-utt-border.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setPreferredSize(new java.awt.Dimension(1303, 563));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("TRA CỨU SÁCH");

        jPanel8.setBackground(new java.awt.Color(255, 255, 204));
        jPanel8.setPreferredSize(new java.awt.Dimension(1309, 500));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel26.setText("Tìm kiếm Sách:");

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton7.setText("Tìm kiếm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txtTimS.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        rbtTS.setText("Theo tên sách");

        rbtTG.setText("Theo tác giả");

        rbtNXB.setText("Theo nhà xuất bản");

        tblTraC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTraC);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(34, 34, 34)
                                .addComponent(txtTimS, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jButton7))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(rbtTS)
                                .addGap(54, 54, 54)
                                .addComponent(rbtTG, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(rbtNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jButton7)
                    .addComponent(txtTimS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtTS)
                    .addComponent(rbtTG)
                    .addComponent(rbtNXB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(jLabel1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        jMenuBar1.setBackground(new java.awt.Color(224, 246, 249));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenu1.setForeground(new java.awt.Color(0, 0, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/trangchu.png"))); // NOI18N
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        menu_dangxuat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        menu_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/exit18.png"))); // NOI18N
        menu_dangxuat.setText("Đăng xuất");
        menu_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_dangxuatActionPerformed(evt);
            }
        });
        jMenu1.add(menu_dangxuat);

        menu_thoat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        menu_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/power-button 18.png"))); // NOI18N
        menu_thoat.setText("Thoát");
        menu_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_thoatActionPerformed(evt);
            }
        });
        jMenu1.add(menu_thoat);

        jMenuItem6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/icons8-password-reset-18.png"))); // NOI18N
        jMenuItem6.setText("Đổi mật khẩu");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/docgia32x.png"))); // NOI18N
        jMenu2.setText("Quản lý độc giả");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem1.setText("Quản lý độc giả");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem2.setText("Tìm kiếm thông tin độc giả");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(0, 0, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/book.png"))); // NOI18N
        jMenu3.setText("Quản lý sách");
        jMenu3.setDoubleBuffered(true);
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem3.setText("Quản lý sách");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem4.setText("Quản lý thể loại");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(0, 0, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/exchange1.png"))); // NOI18N
        jMenu4.setText("Quản lý mượn trả");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem5.setText("Quản lý phiếu mượn");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        munu_qltt.setForeground(new java.awt.Color(0, 0, 255));
        munu_qltt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/librarian.png"))); // NOI18N
        munu_qltt.setText("Quản lý thủ thư");
        munu_qltt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem8.setText("Quản lý thủ thư");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        munu_qltt.add(jMenuItem8);

        jMenuBar1.add(munu_qltt);

        jMenu6.setForeground(new java.awt.Color(0, 0, 255));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/thongke.png"))); // NOI18N
        jMenu6.setText("Thống Kê");
        jMenu6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem10.setText("Thống kê sách");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem11.setText("Thống kê tiền mượn sách");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem11);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1329, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1329, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public trangchuthuvien(String quyen){
        initComponents();
        if (quyen == "Thủ Thư") {
            munu_qltt.setEnabled(false); 
        } else {
            munu_qltt.setEnabled(true); 
        }
        this.setLocationRelativeTo(null);
        hienthi();
    }
    private void menu_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_dangxuatActionPerformed
        new dangnhap().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menu_dangxuatActionPerformed

    private void menu_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_thoatActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Bạn có chắc chẵn muốn thoát ?");
        if(result == 0){
            this.dispose();
        }
    }//GEN-LAST:event_menu_thoatActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        frmqlphieumuon frmqlpm = new frmqlphieumuon();
        frmqlpm.setVisible(true);
        this.setVisible(false);
       
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        qlydocgia fqldg= new qlydocgia();
        fqldg.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        qlthuthu qltt= new qlthuthu();
        qltt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
       frmTKS tKS = new frmTKS();
       tKS.setVisible(true);
       this.setEnabled(false);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        thongketien thongkehd = new thongketien();
        thongkehd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       tkthongtindg tkttdg= new tkthongtindg();
        tkttdg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        frmSachql qlys = new frmSachql();
        qlys.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        frmTheL frmtl = new frmTheL();
        frmtl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(txtTimS.getText().equals("")){
            try {
                tblTraC.removeAll();
                String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
                DefaultTableModel model;
                model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .

                Connection connection =  DBconnection.geConnection();
                String query = "SELECT * FROM Sach";

                java.sql.Statement statement =  connection.createStatement();
                ResultSet rs = statement.executeQuery(query);
                while(rs.next()) {
                    Vector vct = new Vector();
                    vct.add(rs.getString("mas"));
                    vct.add(rs.getString("tensach"));
                    vct.add(rs.getString("matl"));
                    vct.add(rs.getString("tacgia"));
                    vct.add(rs.getString("nhaxb"));
                    vct.add(rs.getString("namxb"));
                    vct.add(rs.getString("giasach"));
                    vct.add(rs.getString("soluong"));
                    vct.add(rs.getString("tomtat"));
                    model.addRow(vct);
                    tblTraC.setModel(model);
                }
            } catch (Exception e) {
            }
        }
        else{
            if(rbtTS.isSelected()==true){
                try {
                    tblTraC.removeAll();
                    String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
                    DefaultTableModel model;
                    model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .

                    Connection connection =  DBconnection.geConnection();
                    String query = "SELECT * FROM Sach where tensach like N'%"+txtTimS.getText()+"%'";

                    java.sql.Statement statement =  connection.createStatement();
                    ResultSet rs = statement.executeQuery(query);
                    while(rs.next()) {
                        Vector vct = new Vector();
                        vct.add(rs.getString("mas"));
                        vct.add(rs.getString("tensach"));
                        vct.add(rs.getString("matl"));
                        vct.add(rs.getString("tacgia"));
                        vct.add(rs.getString("nhaxb"));
                        vct.add(rs.getString("namxb"));
                        vct.add(rs.getString("giasach"));
                        vct.add(rs.getString("soluong"));
                        vct.add(rs.getString("tomtat"));
                        model.addRow(vct);
                        tblTraC.setModel(model);
                    }
                } catch (Exception e) {
                }
            }else if(rbtNXB.isSelected()==true){
                try {
                    tblTraC.removeAll();
                    String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
                    DefaultTableModel model;
                    model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .

                    Connection connection =  DBconnection.geConnection();
                    String query = "SELECT * FROM Sach where nhaxb like N'%"+txtTimS.getText()+"%'";

                    java.sql.Statement statement =  connection.createStatement();
                    ResultSet rs = statement.executeQuery(query);
                    while(rs.next()) {
                        Vector vct = new Vector();
                        vct.add(rs.getString("mas"));
                        vct.add(rs.getString("tensach"));
                        vct.add(rs.getString("matl"));
                        vct.add(rs.getString("tacgia"));
                        vct.add(rs.getString("nhaxb"));
                        vct.add(rs.getString("namxb"));
                        vct.add(rs.getString("giasach"));
                        vct.add(rs.getString("soluong"));
                        vct.add(rs.getString("tomtat"));
                        model.addRow(vct);
                        tblTraC.setModel(model);
                    }
                } catch (Exception e) {
                }
            }else if(rbtTG.isSelected()==true){
                try {
                    tblTraC.removeAll();
                    String [] arr = {"Mã Sách","Tên Sách","Mã Thể Loại","Tác Giả","Nhà XB","Năm XB","Giá","Số Lượng","Tóm Tắt"};
                    DefaultTableModel model;
                    model = new DefaultTableModel(arr, 0); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một > Vector > Vectors .

                    Connection connection =  DBconnection.geConnection();
                    String query = "SELECT * FROM Sach where tacgia like N'%"+txtTimS.getText()+"%'";

                    java.sql.Statement statement =  connection.createStatement();
                    ResultSet rs = statement.executeQuery(query);
                    while(rs.next()) {
                        Vector vct = new Vector();
                        vct.add(rs.getString("mas"));
                        vct.add(rs.getString("tensach"));
                        vct.add(rs.getString("matl"));
                        vct.add(rs.getString("tacgia"));
                        vct.add(rs.getString("nhaxb"));
                        vct.add(rs.getString("namxb"));
                        vct.add(rs.getString("giasach"));
                        vct.add(rs.getString("soluong"));
                        vct.add(rs.getString("tomtat"));
                        model.addRow(vct);
                        tblTraC.setModel(model);
                    }
                } catch (Exception e) {
                }
            }

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        frmDoiMK doiMK = new frmDoiMK();
        doiMK.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trangchuthuvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trangchuthuvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trangchuthuvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trangchuthuvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trangchuthuvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menu_dangxuat;
    private javax.swing.JMenuItem menu_thoat;
    private javax.swing.JMenu munu_qltt;
    private javax.swing.JRadioButton rbtNXB;
    private javax.swing.JRadioButton rbtTG;
    private javax.swing.JRadioButton rbtTS;
    private javax.swing.JTable tblTraC;
    private javax.swing.JTextField txtTimS;
    // End of variables declaration//GEN-END:variables
}
